/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import SecureAccessFenceTypes;

interface OHOS.Security.SecureAccessFence.ISecureAccessFence {
    /**
     * @brief Batch generate tickets.
     * @param osAccountId OS account ID.
     * @param callerId Caller identifier (appIdentifyId).
     * @param messages List of messages to generate tickets for.
     * @param ticketInfos List of generated ticket info (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 1] void BatchGenerateTicket(
        [in] unsigned int osAccountId,
        [in] String callerId,
        [in] List<String> messages,
        [out] List<VerifyTicketInfo> ticketInfos,
        [out] int resultCode
    );

    /**
     * @brief Batch verify tickets.
     * @param osAccountId OS account ID.
     * @param callerId Caller identifier (appIdentifyId).
     * @param verifyInfos List of verify ticket info to verify.
     * @param verifyRes List of verify results (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 2] void BatchVerifyTicket(
        [in] unsigned int osAccountId,
        [in] String callerId,
        [in] List<VerifyTicketInfo> verifyInfos,
        [out] List<int> verifyRes,
        [out] int resultCode
    );

    /**
     * @brief Batch query permissions by sub-commands.
     * @param cmds List of commands to query (input parameter).
     * @param cmdPermissions List of permission results (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 500] void QueryPermissionBySubCommandBatch(
        [in] List<Command> cmds,
        [out] List<CommandPermission> cmdPermissions,
        [out] int resultCode
    );
};