/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import SecureAccessFenceType;

interface OHOS.Security.SAF.ISecureAccessFence {
    /**
     * @brief Batch generate tickets.
     * @param osAccountId OS account ID.
     * @param callerId Caller identifier (appIdentifyId).
     * @param messages List of messages to generate tickets for.
     * @param ticketInfos List of generated ticket info (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 1] void BatchGenerateTicket(
        [in] int osAccountId,
        [in] String callerId,
        [in] List<String> messages,
        [out] List<VerifyTicketInfo> ticketInfos,
        [out] int resultCode
    );

    /**
     * @brief Batch verify tickets.
     * @param osAccountId OS account ID.
     * @param callerId Caller identifier (appIdentifyId).
     * @param verifyInfos List of verify ticket info to verify.
     * @param verifyRes List of verify results (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 2] void BatchVerifyTicket(
        [in] int osAccountId,
        [in] String callerId,
        [in] List<VerifyTicketInfo> verifyInfos,
        [out] List<int> verifyRes,
        [out] int resultCode
    );

    [ipccode 3] void VerifyTicket(
        [in] int osAccountId,
        [in] String callerId,
        [in] String verifyInfo,
        [out] List<CliInfo> cliInfos,
        [out] int resultCode
    );

    /**
     * @brief Generate controlled device packages for remote control scenario.
     * @param permissionQuery List of permission queries.
     * @param remoteAuthPackage List of generated remote auth packages (output parameter).
     */
    [ipccode 4] void GenerateControlledDevicePackage(
        [in] List<PermissionQuery> permissionQuery,
        [out] List<RemoteAuthPackage> remoteAuthPackage,
        [out] int resultCode
    );

    /**
     * @brief Verify controlled device packages for remote control scenario.
     * @param ticketInfo List of remote auth packages to verify.
     * @param verifyRes List of verification results (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 5] void VerifyControlledDevicePackage(
        [in] List<RemoteAuthPackage> ticketInfo,
        [out] List<boolean> verifyRes,
        [out] int resultCode
    );
    
    /**
     * @brief Generate controller device packages for remote control scenario.
     * @param remoteUserAuthResults List of remote user authentication results.
     * @param remoteAuthPackage List of generated remote auth packages (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 6] void GenerateControllerDevicePackage(
        [in] List<RemoteUserAuthResults> remoteUserAuthResults,
        [out] List<RemoteAuthPackage> remoteAuthPackage,
        [out] int resultCode
    );

    /**
     * @brief Verify controller device packages for remote control scenario.
     * @param ticketInfo List of remote auth packages to verify.
     * @param remoteInfo Remote information for verification.
     * @param verifyRes List of verification results (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 7] void VerifyControllerDevicePackage(
        [in] List<RemoteAuthPackage> ticketInfo,
        [in] RemoteInfo remoteInfo,
        [out] List<boolean> verifyRes,
        [out] int resultCode
    );

    /**
     * @brief Batch query command permissions.
     * @param cmds List of commands to query (input parameter).
     * @param cmdPermissions List of permission results (output parameter).
     * @param resultCode Error code output (0 for success).
     */
    [ipccode 500] void BatchQueryCommandPermission(
        [in] List<CommandInfo> cmds,
        [out] List<CommandPermissionInfo> cmdPermissions,
        [out] int resultCode
    );

    [ipccode 501] int RequestToolPermissions(
        [in] PermissionQuery permissionQuery,
        [out] PermissionQueryResult permissionQueryResult
    );

    [ipccode 502] int GrantToolPermissionsByUser(
        [in] List<UserAuthResult> userAuthResult,
        [out] List<VerifyTicketInfo> ticketInfo
    );
};